/*
 *		STP_Show.c
 *
 *      Author: Yasmeen
 */

#include "STD.h"
#include "BIT_Math.h"
#include "STP.h"
#include "STP_Show.h"
//#include "TIMER_Interface.h"
#include "MSYSTICK.h"


void Hamoksha(void)
{
	for(int i=0;i<8;i++)
	{

		STP_SendSynch(0xFE1C);
		//
		STP_SendSynch(0xFD14);
		//
		STP_SendSynch(0xFB9C);
		//
		STP_SendSynch(0xF748);
		//
		STP_SendSynch(0xEF3E);
		//
		STP_SendSynch(0xDF09);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F22);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE0E);
		//
		STP_SendSynch(0xFD0A);
		//
		STP_SendSynch(0xFB4E);
		//
		STP_SendSynch(0xF724);
		//
		STP_SendSynch(0xEF1F);
		//
		STP_SendSynch(0xDF84);
		//
		STP_SendSynch(0xBF0E);
		//
		STP_SendSynch(0x7F11);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE07);
		//
		STP_SendSynch(0xFD05);
		//
		STP_SendSynch(0xFB27);
		//
		STP_SendSynch(0xF712);
		//
		STP_SendSynch(0xEF8F);
		//
		STP_SendSynch(0xDF42);
		//
		STP_SendSynch(0xBF07);
		//
		STP_SendSynch(0x7F88);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE83);
		//
		STP_SendSynch(0xFD82);
		//
		STP_SendSynch(0xFB93);
		//
		STP_SendSynch(0xF709);
		//
		STP_SendSynch(0xEFC7);
		//
		STP_SendSynch(0xDF21);
		//
		STP_SendSynch(0xBF83);
		//
		STP_SendSynch(0x7F44);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////////////////
		STP_SendSynch(0xFEC1);
		//
		STP_SendSynch(0xFD41);
		//
		STP_SendSynch(0xFBC9);
		//
		STP_SendSynch(0xF784);
		//
		STP_SendSynch(0xEFE3);
		//
		STP_SendSynch(0xDF90);
		//
		STP_SendSynch(0xBFC1);
		//
		STP_SendSynch(0x7F22);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFEE0);
		//
		STP_SendSynch(0xFDA0);
		//
		STP_SendSynch(0xFBE4);
		//
		STP_SendSynch(0xF742);
		//
		STP_SendSynch(0xEFF1);
		//
		STP_SendSynch(0xDF48);
		//
		STP_SendSynch(0xBFE0);
		//
		STP_SendSynch(0x7F11);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE70);
		//
		STP_SendSynch(0xFD50);
		//
		STP_SendSynch(0xFB72);
		//
		STP_SendSynch(0xF721);
		//
		STP_SendSynch(0xEFF8);
		//
		STP_SendSynch(0xDF24);
		//
		STP_SendSynch(0xBF70);
		//
		STP_SendSynch(0x7F88);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE38);
		//
		STP_SendSynch(0xFD28);
		//
		STP_SendSynch(0xFB39);
		//
		STP_SendSynch(0xF790);
		//
		STP_SendSynch(0xEF7C);
		//
		STP_SendSynch(0xDF12);
		//
		STP_SendSynch(0xBF38);
		//
		STP_SendSynch(0x7F44);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE1C);
		//
		STP_SendSynch(0xFD14);
		//
		STP_SendSynch(0xFB9C);
		//
		STP_SendSynch(0xF748);
		//
		STP_SendSynch(0xEF3E);
		//
		STP_SendSynch(0xDF09);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F22);
		TIM2_voidSetBusyWait(300);
	}

}

void NoteMusic(void)
{
	for(int i=0;i<8;i++)
	{
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0C);
		//
		STP_SendSynch(0xFB1C);
		//
		STP_SendSynch(0xF714);
		//
		STP_SendSynch(0xEF04);
		//
		STP_SendSynch(0xDF07);
		//
		STP_SendSynch(0xBF07);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD06);
		//
		STP_SendSynch(0xFB0E);
		//
		STP_SendSynch(0xF70A);
		//
		STP_SendSynch(0xEF02);
		//
		STP_SendSynch(0xDF83);
		//
		STP_SendSynch(0xBF83);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD03);
		//
		STP_SendSynch(0xFB07);
		//
		STP_SendSynch(0xF705);
		//
		STP_SendSynch(0xEF01);
		//
		STP_SendSynch(0xDFC1);
		//
		STP_SendSynch(0xBFC1);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD81);
		//
		STP_SendSynch(0xFB83);
		//
		STP_SendSynch(0xF782);
		//
		STP_SendSynch(0xEF80);
		//
		STP_SendSynch(0xDFE0);
		//
		STP_SendSynch(0xBFE0);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		////////
		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDC0);
		//
		STP_SendSynch(0xFBC1);
		//
		STP_SendSynch(0xF741);
		//
		STP_SendSynch(0xEF40);
		//
		STP_SendSynch(0xDF70);
		//
		STP_SendSynch(0xBF70);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD60);
		//
		STP_SendSynch(0xFBE0);
		//
		STP_SendSynch(0xF7A0);
		//
		STP_SendSynch(0xEF20);
		//
		STP_SendSynch(0xDF38);
		//
		STP_SendSynch(0xBF38);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD30);
		//
		STP_SendSynch(0xFB70);
		//
		STP_SendSynch(0xF750);
		//
		STP_SendSynch(0xEF10);
		//
		STP_SendSynch(0xDF1C);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD18);
		//
		STP_SendSynch(0xFB38);
		//
		STP_SendSynch(0xF728);
		//
		STP_SendSynch(0xEF08);
		//
		STP_SendSynch(0xDF0E);
		//
		STP_SendSynch(0xBF0E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//music note
		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0C);
		//
		STP_SendSynch(0xFB1C);
		//
		STP_SendSynch(0xF714);
		//
		STP_SendSynch(0xEF04);
		//
		STP_SendSynch(0xDF07);
		//
		STP_SendSynch(0xBF07);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

	}
}

void Show_Cairokee(void)
{
	for(int i=0;i<8;i++)
	{
		/////////////////////////// C ///////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD78);
		//
		STP_SendSynch(0xFB04);
		//
		STP_SendSynch(0xF702);
		//
		STP_SendSynch(0xEF02);
		//
		STP_SendSynch(0xDF04);
		//
		STP_SendSynch(0xBF78);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD3C);
		//
		STP_SendSynch(0xFB02);
		//
		STP_SendSynch(0xF701);
		//
		STP_SendSynch(0xEF01);
		//
		STP_SendSynch(0xDF02);
		//
		STP_SendSynch(0xBF3C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD1E);
		//
		STP_SendSynch(0xFB01);
		//
		STP_SendSynch(0xF780);
		//
		STP_SendSynch(0xEF80);
		//
		STP_SendSynch(0xDF01);
		//
		STP_SendSynch(0xBF1E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0F);
		//
		STP_SendSynch(0xFB80);
		//
		STP_SendSynch(0xF740);
		//
		STP_SendSynch(0xEF40);
		//
		STP_SendSynch(0xDF80);
		//
		STP_SendSynch(0xBF0F);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD87);
		//
		STP_SendSynch(0xFB40);
		//
		STP_SendSynch(0xF720);
		//
		STP_SendSynch(0xEF20);
		//
		STP_SendSynch(0xDF40);
		//
		STP_SendSynch(0xBF87);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDC3);
		//
		STP_SendSynch(0xFB20);
		//
		STP_SendSynch(0xF710);
		//
		STP_SendSynch(0xEF10);
		//
		STP_SendSynch(0xDF20);
		//
		STP_SendSynch(0xBFC3);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDE1);
		//
		STP_SendSynch(0xFB10);
		//
		STP_SendSynch(0xF708);
		//
		STP_SendSynch(0xEF08);
		//
		STP_SendSynch(0xDF10);
		//
		STP_SendSynch(0xBFE1);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDF0);
		//
		STP_SendSynch(0xFB08);
		//
		STP_SendSynch(0xF704);
		//
		STP_SendSynch(0xEF04);
		//
		STP_SendSynch(0xDF08);
		//
		STP_SendSynch(0xBFF0);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD78);
		//
		STP_SendSynch(0xFB04);
		//
		STP_SendSynch(0xF702);
		//
		STP_SendSynch(0xEF02);
		//
		STP_SendSynch(0xDF04);
		//
		STP_SendSynch(0xBF78);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		///////////O  /////////////////////////////////


		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD1C);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0E);
		//
		STP_SendSynch(0xFB11);
		//
		STP_SendSynch(0xF711);
		//
		STP_SendSynch(0xEF11);
		//
		STP_SendSynch(0xDF11);
		//
		STP_SendSynch(0xBF0E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD07);
		//
		STP_SendSynch(0xFB88);
		//
		STP_SendSynch(0xF788);
		//
		STP_SendSynch(0xEF88);
		//
		STP_SendSynch(0xDF88);
		//
		STP_SendSynch(0xBF07);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD83);
		//
		STP_SendSynch(0x44);
		//
		STP_SendSynch(0xF744);
		//
		STP_SendSynch(0xEF44);
		//
		STP_SendSynch(0xDF44);
		//
		STP_SendSynch(0xBF83);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDC1);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBFC1);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDE0);
		//
		STP_SendSynch(0xFB11);
		//
		STP_SendSynch(0xF711);
		//
		STP_SendSynch(0xEF11);
		//
		STP_SendSynch(0xDF11);
		//
		STP_SendSynch(0xBFE0);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD70);
		//
		STP_SendSynch(0xFB88);
		//
		STP_SendSynch(0xF788);
		//
		STP_SendSynch(0x88);
		//
		STP_SendSynch(0xDF88);
		//
		STP_SendSynch(0xBF70);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD38);
		//
		STP_SendSynch(0xFB44);
		//
		STP_SendSynch(0xF744);
		//
		STP_SendSynch(0xEF44);
		//
		STP_SendSynch(0xDF44);
		//
		STP_SendSynch(0xBF38);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD1C);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////// a //////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0E);
		//
		STP_SendSynch(0xFB08);
		//
		STP_SendSynch(0xF70E);
		//
		STP_SendSynch(0xEF0A);
		//
		STP_SendSynch(0xDF0A);
		//
		STP_SendSynch(0xBF0E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD07);
		//
		STP_SendSynch(0xFB04);
		//
		STP_SendSynch(0xF707);
		//
		STP_SendSynch(0xEF05);
		//
		STP_SendSynch(0xDF05);
		//
		STP_SendSynch(0xBF07);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD83);
		//
		STP_SendSynch(0xFB02);
		//
		STP_SendSynch(0xF783);
		//
		STP_SendSynch(0xEF82);
		//
		STP_SendSynch(0xDF82);
		//
		STP_SendSynch(0xBF83);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDC1);
		//
		STP_SendSynch(0xFB01);
		//
		STP_SendSynch(0xF7C1);
		//
		STP_SendSynch(0xEF41);
		//
		STP_SendSynch(0xDF41);
		//
		STP_SendSynch(0xBFC1);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDE0);
		//
		STP_SendSynch(0xFB80);
		//
		STP_SendSynch(0xF7E0);
		//
		STP_SendSynch(0xEFA0);
		//
		STP_SendSynch(0xDFA0);
		//
		STP_SendSynch(0xBFE0);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD70);
		//
		STP_SendSynch(0xFB40);
		//
		STP_SendSynch(0xF770);
		//
		STP_SendSynch(0xEF50);
		//
		STP_SendSynch(0xDF50);
		//
		STP_SendSynch(0xBF70);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD38);
		//
		STP_SendSynch(0xFB20);
		//
		STP_SendSynch(0xF738);
		//
		STP_SendSynch(0xEF28);
		//
		STP_SendSynch(0xDF28);
		//
		STP_SendSynch(0xBF38);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD1C);
		//
		STP_SendSynch(0xFB10);
		//
		STP_SendSynch(0xF71C);
		//
		STP_SendSynch(0xEF14);
		//
		STP_SendSynch(0xDF14);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0E);
		//
		STP_SendSynch(0xFB08);
		//
		STP_SendSynch(0xF70E);
		//
		STP_SendSynch(0xEF0A);
		//
		STP_SendSynch(0xDF0A);
		//
		STP_SendSynch(0xBF0E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////// I ////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD02);
		//
		STP_SendSynch(0xFB00);
		//
		STP_SendSynch(0xF702);
		//
		STP_SendSynch(0xEF02);
		//
		STP_SendSynch(0xDF02);
		//
		STP_SendSynch(0xBF02);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD01);
		//
		STP_SendSynch(0xFB00);
		//
		STP_SendSynch(0xF701);
		//
		STP_SendSynch(0xEF01);
		//
		STP_SendSynch(0xDF01);
		//
		STP_SendSynch(0xBF01);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD80);
		//
		STP_SendSynch(0xFB00);
		//
		STP_SendSynch(0xF780);
		//
		STP_SendSynch(0xEF80);
		//
		STP_SendSynch(0xDF80);
		//
		STP_SendSynch(0xBF80);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD40);
		//
		STP_SendSynch(0xFB00);
		//
		STP_SendSynch(0xF740);
		//
		STP_SendSynch(0xEF40);
		//
		STP_SendSynch(0xDF40);
		//
		STP_SendSynch(0xBF40);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD20);
		//
		STP_SendSynch(0xFB00);
		//
		STP_SendSynch(0xF720);
		//
		STP_SendSynch(0xEF20);
		//
		STP_SendSynch(0xDF20);
		//
		STP_SendSynch(0xBF20);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD10);
		//
		STP_SendSynch(0xFB00);
		//
		STP_SendSynch(0xF710);
		//
		STP_SendSynch(0xEF10);
		//
		STP_SendSynch(0xDF10);
		//
		STP_SendSynch(0xBF10);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD08);
		//
		STP_SendSynch(0xFB00);
		//
		STP_SendSynch(0xF708);
		//
		STP_SendSynch(0xEF08);
		//
		STP_SendSynch(0xDF08);
		//
		STP_SendSynch(0xBF08);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD04);
		//
		STP_SendSynch(0xFB00);
		//
		STP_SendSynch(0xF704);
		//
		STP_SendSynch(0xEF04);
		//
		STP_SendSynch(0xDF04);
		//
		STP_SendSynch(0xBF04);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0E);
		//
		STP_SendSynch(0xFB08);
		//
		STP_SendSynch(0xF70E);
		//
		STP_SendSynch(0xEF0A);
		//
		STP_SendSynch(0xDF0A);
		//
		STP_SendSynch(0xBF0E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////// r //////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD12);
		//
		STP_SendSynch(0xFB0A);
		//
		STP_SendSynch(0xF706);
		//
		STP_SendSynch(0xEF02);
		//
		STP_SendSynch(0xDF02);
		//
		STP_SendSynch(0xBF02);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD09);
		//
		STP_SendSynch(0xFB05);
		//
		STP_SendSynch(0xF703);
		//
		STP_SendSynch(0xEF01);
		//
		STP_SendSynch(0xDF01);
		//
		STP_SendSynch(0xBF01);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD84);
		//
		STP_SendSynch(0xFB82);
		//
		STP_SendSynch(0xF781);
		//
		STP_SendSynch(0xEF80);
		//
		STP_SendSynch(0xDF80);
		//
		STP_SendSynch(0xBF80);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD42);
		//
		STP_SendSynch(0xFB41);
		//
		STP_SendSynch(0xF7C0);
		//
		STP_SendSynch(0xEF40);
		//
		STP_SendSynch(0xDF40);
		//
		STP_SendSynch(0xBF40);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD21);
		//
		STP_SendSynch(0xFBA0);
		//
		STP_SendSynch(0xF760);
		//
		STP_SendSynch(0xEF20);
		//
		STP_SendSynch(0xDF20);
		//
		STP_SendSynch(0xBF20);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD90);
		//
		STP_SendSynch(0xFB50);
		//
		STP_SendSynch(0xF730);
		//
		STP_SendSynch(0xEF10);
		//
		STP_SendSynch(0xDF10);
		//
		STP_SendSynch(0xBF10);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD48);
		//
		STP_SendSynch(0xFB28);
		//
		STP_SendSynch(0xF718);
		//
		STP_SendSynch(0xEF08);
		//
		STP_SendSynch(0xDF08);
		//
		STP_SendSynch(0xBF08);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD24);
		//
		STP_SendSynch(0xFB14);
		//
		STP_SendSynch(0xF70C);
		//
		STP_SendSynch(0xEF04);
		//
		STP_SendSynch(0xDF04);
		//
		STP_SendSynch(0xBF04);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD12);
		//
		STP_SendSynch(0xFB0A);
		//
		STP_SendSynch(0xF706);
		//
		STP_SendSynch(0xEF02);
		//
		STP_SendSynch(0xDF02);
		//
		STP_SendSynch(0xBF02);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		///////////O  /////////////////////////////////


		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD1C);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0E);
		//
		STP_SendSynch(0xFB11);
		//
		STP_SendSynch(0xF711);
		//
		STP_SendSynch(0xEF11);
		//
		STP_SendSynch(0xDF11);
		//
		STP_SendSynch(0xBF0E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD07);
		//
		STP_SendSynch(0xFB88);
		//
		STP_SendSynch(0xF788);
		//
		STP_SendSynch(0xEF88);
		//
		STP_SendSynch(0xDF88);
		//
		STP_SendSynch(0xBF07);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD83);
		//
		STP_SendSynch(0x44);
		//
		STP_SendSynch(0xF744);
		//
		STP_SendSynch(0xEF44);
		//
		STP_SendSynch(0xDF44);
		//
		STP_SendSynch(0xBF83);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDC1);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBFC1);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDE0);
		//
		STP_SendSynch(0xFB11);
		//
		STP_SendSynch(0xF711);
		//
		STP_SendSynch(0xEF11);
		//
		STP_SendSynch(0xDF11);
		//
		STP_SendSynch(0xBFE0);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD70);
		//
		STP_SendSynch(0xFB88);
		//
		STP_SendSynch(0xF788);
		//
		STP_SendSynch(0x88);
		//
		STP_SendSynch(0xDF88);
		//
		STP_SendSynch(0xBF70);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD38);
		//
		STP_SendSynch(0xFB44);
		//
		STP_SendSynch(0xF744);
		//
		STP_SendSynch(0xEF44);
		//
		STP_SendSynch(0xDF44);
		//
		STP_SendSynch(0xBF38);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD1C);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		///////////O  /////////////////////////////////


		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD1C);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0E);
		//
		STP_SendSynch(0xFB11);
		//
		STP_SendSynch(0xF711);
		//
		STP_SendSynch(0xEF11);
		//
		STP_SendSynch(0xDF11);
		//
		STP_SendSynch(0xBF0E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD07);
		//
		STP_SendSynch(0xFB88);
		//
		STP_SendSynch(0xF788);
		//
		STP_SendSynch(0xEF88);
		//
		STP_SendSynch(0xDF88);
		//
		STP_SendSynch(0xBF07);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD83);
		//
		STP_SendSynch(0x44);
		//
		STP_SendSynch(0xF744);
		//
		STP_SendSynch(0xEF44);
		//
		STP_SendSynch(0xDF44);
		//
		STP_SendSynch(0xBF83);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDC1);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBFC1);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDE0);
		//
		STP_SendSynch(0xFB11);
		//
		STP_SendSynch(0xF711);
		//
		STP_SendSynch(0xEF11);
		//
		STP_SendSynch(0xDF11);
		//
		STP_SendSynch(0xBFE0);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD70);
		//
		STP_SendSynch(0xFB88);
		//
		STP_SendSynch(0xF788);
		//
		STP_SendSynch(0x88);
		//
		STP_SendSynch(0xDF88);
		//
		STP_SendSynch(0xBF70);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD38);
		//
		STP_SendSynch(0xFB44);
		//
		STP_SendSynch(0xF744);
		//
		STP_SendSynch(0xEF44);
		//
		STP_SendSynch(0xDF44);
		//
		STP_SendSynch(0xBF38);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD1C);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		///////////////////////////// O ////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD1C);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0E);
		//
		STP_SendSynch(0xFB11);
		//
		STP_SendSynch(0xF711);
		//
		STP_SendSynch(0xEF11);
		//
		STP_SendSynch(0xDF11);
		//
		STP_SendSynch(0xBF0E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD07);
		//
		STP_SendSynch(0xFB88);
		//
		STP_SendSynch(0xF788);
		//
		STP_SendSynch(0xEF88);
		//
		STP_SendSynch(0xDF88);
		//
		STP_SendSynch(0xBF07);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD83);
		//
		STP_SendSynch(0x44);
		//
		STP_SendSynch(0xF744);
		//
		STP_SendSynch(0xEF44);
		//
		STP_SendSynch(0xDF44);
		//
		STP_SendSynch(0xBF83);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDC1);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBFC1);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDE0);
		//
		STP_SendSynch(0xFB11);
		//
		STP_SendSynch(0xF711);
		//
		STP_SendSynch(0xEF11);
		//
		STP_SendSynch(0xDF11);
		//
		STP_SendSynch(0xBFE0);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD70);
		//
		STP_SendSynch(0xFB88);
		//
		STP_SendSynch(0xF788);
		//
		STP_SendSynch(0x88);
		//
		STP_SendSynch(0xDF88);
		//
		STP_SendSynch(0xBF70);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD38);
		//
		STP_SendSynch(0xFB44);
		//
		STP_SendSynch(0xF744);
		//
		STP_SendSynch(0xEF44);
		//
		STP_SendSynch(0xDF44);
		//
		STP_SendSynch(0xBF38);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD1C);
		//
		STP_SendSynch(0xFB22);
		//
		STP_SendSynch(0xF722);
		//
		STP_SendSynch(0xEF22);
		//
		STP_SendSynch(0xDF22);
		//
		STP_SendSynch(0xBF1C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		//////////////////////////  k //////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD12);
		//
		STP_SendSynch(0xFB0A);
		//
		STP_SendSynch(0xF706);
		//
		STP_SendSynch(0xEF0A);
		//
		STP_SendSynch(0xDF12);
		//
		STP_SendSynch(0xBF02);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD09);
		//
		STP_SendSynch(0xFB05);
		//
		STP_SendSynch(0xF703);
		//
		STP_SendSynch(0xEF05);
		//
		STP_SendSynch(0xDF09);
		//
		STP_SendSynch(0xBF01);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD84);
		//
		STP_SendSynch(0xFB82);
		//
		STP_SendSynch(0xF781);
		//
		STP_SendSynch(0xEF82);
		//
		STP_SendSynch(0xDF84);
		//
		STP_SendSynch(0xBF80);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD42);
		//
		STP_SendSynch(0xFB41);
		//
		STP_SendSynch(0xF7C0);
		//
		STP_SendSynch(0xEF41);
		//
		STP_SendSynch(0xDF42);
		//
		STP_SendSynch(0xBF40);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		////////
		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD21);
		//
		STP_SendSynch(0xFBA0);
		//
		STP_SendSynch(0xF760);
		//
		STP_SendSynch(0xEFA0);
		//
		STP_SendSynch(0xDF21);
		//
		STP_SendSynch(0xBF20);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD90);
		//
		STP_SendSynch(0xFB50);
		//
		STP_SendSynch(0xF730);
		//
		STP_SendSynch(0xEF50);
		//
		STP_SendSynch(0xDF90);
		//
		STP_SendSynch(0xBF10);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD48);
		//
		STP_SendSynch(0xFB28);
		//
		STP_SendSynch(0xF718);
		//
		STP_SendSynch(0xEF28);
		//
		STP_SendSynch(0xDF48);
		//
		STP_SendSynch(0xBF08);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD24);
		//
		STP_SendSynch(0xFB14);
		//
		STP_SendSynch(0xF70C);
		//
		STP_SendSynch(0xEF14);
		//
		STP_SendSynch(0xDF24);
		//
		STP_SendSynch(0xBF04);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD12);
		//
		STP_SendSynch(0xFB0A);
		//
		STP_SendSynch(0xF706);
		//
		STP_SendSynch(0xEF0A);
		//
		STP_SendSynch(0xDF12);
		//
		STP_SendSynch(0xBF02);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////  e //////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0C);
		//
		STP_SendSynch(0xFB12);
		//
		STP_SendSynch(0xF712);
		//
		STP_SendSynch(0xEF0E);
		//
		STP_SendSynch(0xDF02);
		//
		STP_SendSynch(0xBF1E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD06);
		//
		STP_SendSynch(0xFB09);
		//
		STP_SendSynch(0xF709);
		//
		STP_SendSynch(0xEF07);
		//
		STP_SendSynch(0xDF01);
		//
		STP_SendSynch(0xBF0F);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD03);
		//
		STP_SendSynch(0xFB84);
		//
		STP_SendSynch(0xF784);
		//
		STP_SendSynch(0xEF83);
		//
		STP_SendSynch(0xDF80);
		//
		STP_SendSynch(0xBF87);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD81);
		//
		STP_SendSynch(0xFB42);
		//
		STP_SendSynch(0xF742);
		//
		STP_SendSynch(0xEFC1);
		//
		STP_SendSynch(0xDF40);
		//
		STP_SendSynch(0xBFC3);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		////////
		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDC0);
		//
		STP_SendSynch(0xFB21);
		//
		STP_SendSynch(0xF721);
		//
		STP_SendSynch(0xEFE0);
		//
		STP_SendSynch(0xDF20);
		//
		STP_SendSynch(0xBFE1);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD60);
		//
		STP_SendSynch(0xFB90);
		//
		STP_SendSynch(0xF790);
		//
		STP_SendSynch(0xEF70);
		//
		STP_SendSynch(0xDF10);
		//
		STP_SendSynch(0xBFF0);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD30);
		//
		STP_SendSynch(0xFB48);
		//
		STP_SendSynch(0xF748);
		//
		STP_SendSynch(0xEF38);
		//
		STP_SendSynch(0xDF08);
		//
		STP_SendSynch(0xBF78);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD18);
		//
		STP_SendSynch(0xFB24);
		//
		STP_SendSynch(0xF724);
		//
		STP_SendSynch(0xEF1C);
		//
		STP_SendSynch(0xDF04);
		//
		STP_SendSynch(0xBF3C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0C);
		//
		STP_SendSynch(0xFB12);
		//
		STP_SendSynch(0xF712);
		//
		STP_SendSynch(0xEF0E);
		//
		STP_SendSynch(0xDF02);
		//
		STP_SendSynch(0xBF1E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		/////////////////// e ////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0C);
		//
		STP_SendSynch(0xFB12);
		//
		STP_SendSynch(0xF712);
		//
		STP_SendSynch(0xEF0E);
		//
		STP_SendSynch(0xDF02);
		//
		STP_SendSynch(0xBF1E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		/////////////////////////////////////////////////////////////////

		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD06);
		//
		STP_SendSynch(0xFB09);
		//
		STP_SendSynch(0xF709);
		//
		STP_SendSynch(0xEF07);
		//
		STP_SendSynch(0xDF01);
		//
		STP_SendSynch(0xBF0F);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD03);
		//
		STP_SendSynch(0xFB84);
		//
		STP_SendSynch(0xF784);
		//
		STP_SendSynch(0xEF83);
		//
		STP_SendSynch(0xDF80);
		//
		STP_SendSynch(0xBF87);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		//////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD81);
		//
		STP_SendSynch(0xFB42);
		//
		STP_SendSynch(0xF742);
		//
		STP_SendSynch(0xEFC1);
		//
		STP_SendSynch(0xDF40);
		//
		STP_SendSynch(0xBFC3);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		////////
		/////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFDC0);
		//
		STP_SendSynch(0xFB21);
		//
		STP_SendSynch(0xF721);
		//
		STP_SendSynch(0xEFE0);
		//
		STP_SendSynch(0xDF20);
		//
		STP_SendSynch(0xBFE1);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD60);
		//
		STP_SendSynch(0xFB90);
		//
		STP_SendSynch(0xF790);
		//
		STP_SendSynch(0xEF70);
		//
		STP_SendSynch(0xDF10);
		//
		STP_SendSynch(0xBFF0);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);

		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD30);
		//
		STP_SendSynch(0xFB48);
		//
		STP_SendSynch(0xF748);
		//
		STP_SendSynch(0xEF38);
		//
		STP_SendSynch(0xDF08);
		//
		STP_SendSynch(0xBF78);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);


		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD18);
		//
		STP_SendSynch(0xFB24);
		//
		STP_SendSynch(0xF724);
		//
		STP_SendSynch(0xEF1C);
		//
		STP_SendSynch(0xDF04);
		//
		STP_SendSynch(0xBF3C);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
		////////////////////////////////////////////
		STP_SendSynch(0xFE00);
		//
		STP_SendSynch(0xFD0C);
		//
		STP_SendSynch(0xFB12);
		//
		STP_SendSynch(0xF712);
		//
		STP_SendSynch(0xEF0E);
		//
		STP_SendSynch(0xDF02);
		//
		STP_SendSynch(0xBF1E);
		//
		STP_SendSynch(0x7F00);
		TIM2_voidSetBusyWait(300);
	}
}

void SHOW_AMR(void)
{
	STP_SendSynch(0xFEF8);
	//
	STP_SendSynch(0xFD24);
	//
	STP_SendSynch(0xFB22);
	//
	STP_SendSynch(0xF722);
	//
	STP_SendSynch(0xEF24);
	//
	STP_SendSynch(0xDFF8);
	//
	STP_SendSynch(0xBF00);
	//
	TIM2_voidSetBusyWait(300);
	//**********
	STP_SendSynch(0xFE24);
	//
	STP_SendSynch(0xFD22);
	//
	STP_SendSynch(0xFB22);
	//
	STP_SendSynch(0xF724);
	//
	STP_SendSynch(0xEFF8);
	//
	STP_SendSynch(0xDF00);
	//
	STP_SendSynch(0xBF00);
	//
	STP_SendSynch(0xBFFC);
	//
	TIM2_voidSetBusyWait(300);
	//*************************
	STP_SendSynch(0xFE22);
	//
	STP_SendSynch(0xFD22);
	//
	STP_SendSynch(0xFB24);
	//
	STP_SendSynch(0xF7F8);
	//
	STP_SendSynch(0xEF00);
	//
	STP_SendSynch(0xDF00);
	//
	STP_SendSynch(0xBFFC);
	//
	STP_SendSynch(0xBF04);
	//
	TIM2_voidSetBusyWait(300);
	//*************************************
	STP_SendSynch(0xFE22);
	//
	STP_SendSynch(0xFD24);
	//
	STP_SendSynch(0xFBF8);
	//
	STP_SendSynch(0xF700);
	//
	STP_SendSynch(0xEF00);
	//
	STP_SendSynch(0xDFFC);
	//
	STP_SendSynch(0xBF04);
	//
	STP_SendSynch(0xBF08);
	//
	TIM2_voidSetBusyWait(300);
	//***************************************
	STP_SendSynch(0xFE24);
	//
	STP_SendSynch(0xFDF8);
	//
	STP_SendSynch(0xFB00);
	//
	STP_SendSynch(0xF700);
	//
	STP_SendSynch(0xEFFC);
	//
	STP_SendSynch(0xDF04);
	//
	STP_SendSynch(0xBF08);
	//
	STP_SendSynch(0xBFF0);
	//
	TIM2_voidSetBusyWait(300);
	//*****************************************
	STP_SendSynch(0xFEF8);
	//
	STP_SendSynch(0xFD00);
	//
	STP_SendSynch(0xFB00);
	//
	STP_SendSynch(0xF7FC);
	//
	STP_SendSynch(0xEF04);
	//
	STP_SendSynch(0xDF08);
	//
	STP_SendSynch(0xBFF0);
	//
	STP_SendSynch(0xBF08);
	//
	TIM2_voidSetBusyWait(300);
	//*********************************************
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFD00);
	//
	STP_SendSynch(0xFBFC);
	//
	STP_SendSynch(0xF704);
	//
	STP_SendSynch(0xEF08);
	//
	STP_SendSynch(0xDFF0);
	//
	STP_SendSynch(0xBF08);
	//
	STP_SendSynch(0xBF04);
	//
	TIM2_voidSetBusyWait(300);
	//**********************************************
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFDFC);
	//
	STP_SendSynch(0xFB04);
	//
	STP_SendSynch(0xF708);
	//
	STP_SendSynch(0xEFF0);
	//
	STP_SendSynch(0xDF08);
	//
	STP_SendSynch(0xBF04);
	//
	STP_SendSynch(0xBFFC);
	//
	TIM2_voidSetBusyWait(300);
	//******************************************
	STP_SendSynch(0xFEFC);
	//
	STP_SendSynch(0xFD04);
	//
	STP_SendSynch(0xFB08);
	//
	STP_SendSynch(0xF7F0);
	//
	STP_SendSynch(0xEF08);
	//
	STP_SendSynch(0xDF04);
	//
	STP_SendSynch(0xBFFC);
	//
	STP_SendSynch(0xBF00);
	//
	TIM2_voidSetBusyWait(300);
	//*****************************************
	STP_SendSynch(0xFE04);
	//
	STP_SendSynch(0xFD08);
	//
	STP_SendSynch(0xFBF0);
	//
	STP_SendSynch(0xF708);
	//
	STP_SendSynch(0xEF04);
	//
	STP_SendSynch(0xDFFC);
	//
	STP_SendSynch(0xBF00);
	//
	STP_SendSynch(0xBFFC);
	//
	TIM2_voidSetBusyWait(300);
	//*******************************************
	STP_SendSynch(0xFE08);
	//
	STP_SendSynch(0xFDF0);
	//
	STP_SendSynch(0xFB08);
	//
	STP_SendSynch(0xF704);
	//
	STP_SendSynch(0xEFFC);
	//
	STP_SendSynch(0xDF00);
	//
	STP_SendSynch(0xBFFC);
	//
	STP_SendSynch(0xBF24);
	//
	TIM2_voidSetBusyWait(300);
	//**************************************
	STP_SendSynch(0xFEF0);
	//
	STP_SendSynch(0xFD08);
	//
	STP_SendSynch(0xFB04);
	//
	STP_SendSynch(0xF7FC);
	//
	STP_SendSynch(0xEF00);
	//
	STP_SendSynch(0xDFFC);
	//
	STP_SendSynch(0xBF24);
	//
	STP_SendSynch(0xBF24);
	//
	TIM2_voidSetBusyWait(300);
	//**********************************
	STP_SendSynch(0xFE08);
	//
	STP_SendSynch(0xFD04);
	//
	STP_SendSynch(0xFBFC);
	//
	STP_SendSynch(0xF700);
	//
	STP_SendSynch(0xEFFC);
	//
	STP_SendSynch(0xDF24);
	//
	STP_SendSynch(0xBF24);
	//
	STP_SendSynch(0xBF58);
	//
	TIM2_voidSetBusyWait(300);
	//******************************
	STP_SendSynch(0xFE04);
	//
	STP_SendSynch(0xFDFC);
	//
	STP_SendSynch(0xFB00);
	//
	STP_SendSynch(0xF7FC);
	//
	STP_SendSynch(0xEF24);
	//
	STP_SendSynch(0xDF24);
	//
	STP_SendSynch(0xBF58);
	//
	STP_SendSynch(0xBF80);
	//
	TIM2_voidSetBusyWait(300);
	//*****************************
	STP_SendSynch(0xFEFC);
	//
	STP_SendSynch(0xFD00);
	//
	STP_SendSynch(0xFBFC);
	//
	STP_SendSynch(0xF724);
	//
	STP_SendSynch(0xEF24);
	//
	STP_SendSynch(0xDF58);
	//
	STP_SendSynch(0xBF80);
	//
	STP_SendSynch(0xBF00);
	//
	TIM2_voidSetBusyWait(300);
	//******************************
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFDFC);
	//
	STP_SendSynch(0xFB24);
	//
	STP_SendSynch(0xF724);
	//
	STP_SendSynch(0xEF58);
	//
	STP_SendSynch(0xDF80);
	//
	STP_SendSynch(0xBF00);
	//
	STP_SendSynch(0xBFFC);
	//
	TIM2_voidSetBusyWait(300);
	//*****************************
	STP_SendSynch(0xFEFC);
	//
	STP_SendSynch(0xFD24);
	//
	STP_SendSynch(0xFB24);
	//
	STP_SendSynch(0xF758);
	//
	STP_SendSynch(0xEF80);
	//
	STP_SendSynch(0xDF00);
	//
	STP_SendSynch(0xBFFC);
	//
	STP_SendSynch(0xBF54);
	//
	TIM2_voidSetBusyWait(300);
	//*****************************
	STP_SendSynch(0xFE24);
	//
	STP_SendSynch(0xFD24);
	//
	STP_SendSynch(0xFB58);
	//
	STP_SendSynch(0xF780);
	//
	STP_SendSynch(0xEF00);
	//
	STP_SendSynch(0xDFFC);
	//
	STP_SendSynch(0xBF84);
	//
	STP_SendSynch(0xBF48);
	//
	TIM2_voidSetBusyWait(300);
	//******************************
	STP_SendSynch(0xFE24);
	//
	STP_SendSynch(0xFD58);
	//
	STP_SendSynch(0xFB80);
	//
	STP_SendSynch(0xF700);
	//
	STP_SendSynch(0xEFFC);
	//
	STP_SendSynch(0xDF84);
	//
	STP_SendSynch(0xBF48);
	//
	STP_SendSynch(0xBF30);
	//
	TIM2_voidSetBusyWait(300);
	//*****************************
	STP_SendSynch(0xFE58);
	//
	STP_SendSynch(0xFD80);
	//
	STP_SendSynch(0xFB00);
	//
	STP_SendSynch(0xF7FC);
	//
	STP_SendSynch(0xEF84);
	//
	STP_SendSynch(0xDF48);
	//
	STP_SendSynch(0xBF30);
	//
	STP_SendSynch(0xBF00);

	//
	TIM2_voidSetBusyWait(300);
	//********************************
	STP_SendSynch(0xFE80);
	//
	STP_SendSynch(0xFD00);
	//
	STP_SendSynch(0xFBFC);
	//
	STP_SendSynch(0xF784);
	//
	STP_SendSynch(0xEF48);
	//
	STP_SendSynch(0xDF30);
	//
	STP_SendSynch(0xBF00);
	//
	STP_SendSynch(0xBFF4);

	//
	TIM2_voidSetBusyWait(300);
	//******************************
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFDFC);
	//
	STP_SendSynch(0xFB84);
	//
	STP_SendSynch(0xF748);
	//
	STP_SendSynch(0xEF30);
	//
	STP_SendSynch(0xDF00);
	//
	STP_SendSynch(0xBFF4);
	//
	STP_SendSynch(0xBF00);
	//
	TIM2_voidSetBusyWait(300);
	//******************************
	STP_SendSynch(0xFEFC);
	//
	STP_SendSynch(0xFD84);
	//
	STP_SendSynch(0xFB48);
	//
	STP_SendSynch(0xF730);
	//
	STP_SendSynch(0xEF00);
	//
	STP_SendSynch(0xDFF4);
	//
	STP_SendSynch(0xBF00);
	//
	STP_SendSynch(0xBFF0);
	//
	TIM2_voidSetBusyWait(300);
	//****************************
	STP_SendSynch(0xFE84);
	//
	STP_SendSynch(0xFD48);
	//
	STP_SendSynch(0xFB30);
	//
	STP_SendSynch(0xF700);
	//
	STP_SendSynch(0xEFF4);
	//
	STP_SendSynch(0xDF00);
	//
	STP_SendSynch(0xBFF0);
	//
	STP_SendSynch(0xBF28);
	//
	TIM2_voidSetBusyWait(300);
	//*****************************
	STP_SendSynch(0xFE48);
	//
	STP_SendSynch(0xFD30);
	//
	STP_SendSynch(0xFB00);
	//
	STP_SendSynch(0xF7F4);
	//
	STP_SendSynch(0xEF00);
	//
	STP_SendSynch(0xDFF0);
	//
	STP_SendSynch(0xBF28);
	//
	STP_SendSynch(0xBF24);
	//
	TIM2_voidSetBusyWait(300);
	//******************************
	STP_SendSynch(0xFE30);
	//
	STP_SendSynch(0xFD00);
	//
	STP_SendSynch(0xFBF4);
	//
	STP_SendSynch(0xF700);
	//
	STP_SendSynch(0xEFF0);
	//
	STP_SendSynch(0xDF28);
	//
	STP_SendSynch(0xBF24);
	//
	STP_SendSynch(0xBF28);
	//
	TIM2_voidSetBusyWait(300);
	//*******************************
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFDF4);
	//
	STP_SendSynch(0xFB00);
	//
	STP_SendSynch(0xF7F0);
	//
	STP_SendSynch(0xEF28);
	//
	STP_SendSynch(0xDF24);
	//
	STP_SendSynch(0xBF28);
	//
	STP_SendSynch(0xBFF0);
	//
	TIM2_voidSetBusyWait(300);
	//*******************************
	STP_SendSynch(0xFEF4);
	//
	STP_SendSynch(0xFD00);
	//
	STP_SendSynch(0xFBF0);
	//
	STP_SendSynch(0xF728);
	//
	STP_SendSynch(0xEF24);
	//
	STP_SendSynch(0xDF28);
	//
	STP_SendSynch(0xBFF0);
	//
	STP_SendSynch(0xBF00);
	//
	TIM2_voidSetBusyWait(300);
	//*******************************
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFDF0);
	//
	STP_SendSynch(0xFB28);
	//
	STP_SendSynch(0xF724);
	//
	STP_SendSynch(0xEF28);
	//
	STP_SendSynch(0xDFF0);
	//
	STP_SendSynch(0xBF00);
	//
	STP_SendSynch(0xBFFC);
	//
	TIM2_voidSetBusyWait(300);
	//******************************
	STP_SendSynch(0xFEF0);
	//
	STP_SendSynch(0xFD28);
	//
	STP_SendSynch(0xFB24);
	//
	STP_SendSynch(0xF728);
	//
	STP_SendSynch(0xEFF0);
	//
	STP_SendSynch(0xDF00);
	//
	STP_SendSynch(0xBFFC);
	//
	STP_SendSynch(0xBF90);
	//
	TIM2_voidSetBusyWait(300);
	//******************************
	STP_SendSynch(0xFE28);
	//
	STP_SendSynch(0xFD24);
	//
	STP_SendSynch(0xFB28);
	//
	STP_SendSynch(0xF7F0);
	//
	STP_SendSynch(0xEF00);
	//
	STP_SendSynch(0xDFFC);
	//
	STP_SendSynch(0xBF90);
	//
	STP_SendSynch(0xBFF0);
	//
	TIM2_voidSetBusyWait(300);
}
void Show_Tamer(void)
{
	STP_SendSynch(0xFEFC);
	STP_SendSynch(0xFD24);
	STP_SendSynch(0xFBD8);
	STP_SendSynch(0xF700);
	STP_SendSynch(0xEFF0);
	STP_SendSynch(0xDF28);
	STP_SendSynch(0xBF28);
	STP_SendSynch(0x7FF0);

	STP_SendSynch(0xFE24);
	STP_SendSynch(0xFDD8);
	STP_SendSynch(0xFB00);
	STP_SendSynch(0xF7F0);
	STP_SendSynch(0xEF28);
	STP_SendSynch(0xDF28);
	STP_SendSynch(0xBFF0);
	STP_SendSynch(0x7F00);

	STP_SendSynch(0xFED8);
	STP_SendSynch(0xFD00);
	STP_SendSynch(0xFBF0);
	STP_SendSynch(0xF728);
	STP_SendSynch(0xEF28);
	STP_SendSynch(0xDFF0);
	STP_SendSynch(0xBF00);
	STP_SendSynch(0x7FB8);

	STP_SendSynch(0xFE00);
	STP_SendSynch(0xFDF0);
	STP_SendSynch(0xFB28);
	STP_SendSynch(0xF728);
	STP_SendSynch(0xEFF0);
	STP_SendSynch(0xDF00);
	STP_SendSynch(0xBFB8);
	STP_SendSynch(0x7FA8);

	STP_SendSynch(0xFEF0);
	STP_SendSynch(0xFD28);
	STP_SendSynch(0xFB28);
	STP_SendSynch(0xF7F0);
	STP_SendSynch(0xEF00);
	STP_SendSynch(0xDFB8);
	STP_SendSynch(0xBFA8);
	STP_SendSynch(0x7F84);

	STP_SendSynch(0xFE28);
	STP_SendSynch(0xFD28);
	STP_SendSynch(0xFBF0);
	STP_SendSynch(0xF700);
	STP_SendSynch(0xEFB8);
	STP_SendSynch(0xDFA8);
	STP_SendSynch(0xBF84);
	STP_SendSynch(0x7F00);

	STP_SendSynch(0xFE28);
	STP_SendSynch(0xFDF0);
	STP_SendSynch(0xFB00);
	STP_SendSynch(0xF7B8);
	STP_SendSynch(0xEFA8);
	STP_SendSynch(0xDF84);
	STP_SendSynch(0xBF00);
	STP_SendSynch(0x7FF8);

	STP_SendSynch(0xFEF0);
	STP_SendSynch(0xFD00);
	STP_SendSynch(0xFBB8);
	STP_SendSynch(0xF7A8);
	STP_SendSynch(0xEF84);
	STP_SendSynch(0xDF00);
	STP_SendSynch(0xBFF8);
	STP_SendSynch(0x7F20);

	STP_SendSynch(0xFE00);
	STP_SendSynch(0xFDB8);
	STP_SendSynch(0xFBA8);
	STP_SendSynch(0xF784);
	STP_SendSynch(0xEF00);
	STP_SendSynch(0xDFF8);
	STP_SendSynch(0xBF20);
	STP_SendSynch(0x7F20);

	STP_SendSynch(0xFEB8);
	STP_SendSynch(0xFDA8);
	STP_SendSynch(0xFB84);
	STP_SendSynch(0xF700);
	STP_SendSynch(0xEFF8);
	STP_SendSynch(0xDF20);
	STP_SendSynch(0xBF20);
	STP_SendSynch(0x7FF8);

	STP_SendSynch(0xFEA8);
	STP_SendSynch(0xFD84);
	STP_SendSynch(0xFB00);
	STP_SendSynch(0xF7F8);
	STP_SendSynch(0xEF20);
	STP_SendSynch(0xDF20);
	STP_SendSynch(0xBFF8);
	STP_SendSynch(0x7F00);

	STP_SendSynch(0xFE84);
	STP_SendSynch(0xFD00);
	STP_SendSynch(0xFBF8);
	STP_SendSynch(0xF720);
	STP_SendSynch(0xEF20);
	STP_SendSynch(0xDFF8);
	STP_SendSynch(0xBF00);
	STP_SendSynch(0x7F60);

	STP_SendSynch(0xFE00);
	STP_SendSynch(0xFDF8);
	STP_SendSynch(0xFB20);
	STP_SendSynch(0xF720);
	STP_SendSynch(0xEFF8);
	STP_SendSynch(0xDF00);
	STP_SendSynch(0xBF60);
	STP_SendSynch(0x7F90);

	STP_SendSynch(0xFE00);
	STP_SendSynch(0xFDF8);
	STP_SendSynch(0xFB20);
	STP_SendSynch(0xF720);
	STP_SendSynch(0xEFF8);
	STP_SendSynch(0xDF00);
	STP_SendSynch(0xBF60);
	STP_SendSynch(0x7F90);

	STP_SendSynch(0xFEF8);
	STP_SendSynch(0xFD20);
	STP_SendSynch(0xFB20);
	STP_SendSynch(0xF7F8);
	STP_SendSynch(0xEF00);
	STP_SendSynch(0xDF60);
	STP_SendSynch(0xBF90);
	STP_SendSynch(0x7F90);

	STP_SendSynch(0xFE20);
	STP_SendSynch(0xFD20);
	STP_SendSynch(0xFBF8);
	STP_SendSynch(0xF700);
	STP_SendSynch(0xEF60);
	STP_SendSynch(0xDF90);
	STP_SendSynch(0xBF90);
	STP_SendSynch(0x7F60);

	STP_SendSynch(0xFE20);
	STP_SendSynch(0xFDF8);
	STP_SendSynch(0xFB00);
	STP_SendSynch(0xF760);
	STP_SendSynch(0xEF90);
	STP_SendSynch(0xDF90);
	STP_SendSynch(0xBF60);
	STP_SendSynch(0x7F00);

	STP_SendSynch(0xFEF8);
	STP_SendSynch(0xFD00);
	STP_SendSynch(0xFB60);
	STP_SendSynch(0xF790);
	STP_SendSynch(0xEF90);
	STP_SendSynch(0xDF60);
	STP_SendSynch(0xBF00);
	STP_SendSynch(0x7FE0);

	STP_SendSynch(0xFE00);
	STP_SendSynch(0xFD60);
	STP_SendSynch(0xFB90);
	STP_SendSynch(0xF790);
	STP_SendSynch(0xEF60);
	STP_SendSynch(0xDF00);
	STP_SendSynch(0xBFE0);
	STP_SendSynch(0x7F80);

	STP_SendSynch(0xFE60);
	STP_SendSynch(0xFD90);
	STP_SendSynch(0xFB90);
	STP_SendSynch(0xF760);
	STP_SendSynch(0xEF00);
	STP_SendSynch(0xDFE0);
	STP_SendSynch(0xBF80);
	STP_SendSynch(0x7F80);

	STP_SendSynch(0xFE90);
	STP_SendSynch(0xFD90);
	STP_SendSynch(0xFB60);
	STP_SendSynch(0xF700);
	STP_SendSynch(0xEFE0);
	STP_SendSynch(0xDF80);
	STP_SendSynch(0xBF80);
	STP_SendSynch(0x7FE0);

	STP_SendSynch(0xFE90);
	STP_SendSynch(0xFD60);
	STP_SendSynch(0xFB00);
	STP_SendSynch(0xF7E0);
	STP_SendSynch(0xEF80);
	STP_SendSynch(0xDF80);
	STP_SendSynch(0xBFE0);
	STP_SendSynch(0x7F00);

	STP_SendSynch(0xFE60);
	STP_SendSynch(0xFD00);
	STP_SendSynch(0xFBE0);
	STP_SendSynch(0xF780);
	STP_SendSynch(0xEF80);
	STP_SendSynch(0xDFE0);
	STP_SendSynch(0xBF00);
	STP_SendSynch(0x7FFC);

	STP_SendSynch(0xFE00);
	STP_SendSynch(0xFDE0);
	STP_SendSynch(0xFB80);
	STP_SendSynch(0xF780);
	STP_SendSynch(0xEFE0);
	STP_SendSynch(0xDF00);
	STP_SendSynch(0xBFFC);
	STP_SendSynch(0x7F24);

	STP_SendSynch(0xFEE0);
	STP_SendSynch(0xFD80);
	STP_SendSynch(0xFB80);
	STP_SendSynch(0xF7E0);
	STP_SendSynch(0xEF00);
	STP_SendSynch(0xDFFC);
	STP_SendSynch(0xBF24);
	STP_SendSynch(0x7FD8);

	STP_SendSynch(0xFE80);
	STP_SendSynch(0xFD80);
	STP_SendSynch(0xFBE0);
	STP_SendSynch(0xF700);
	STP_SendSynch(0xEFFC);
	STP_SendSynch(0xDF24);
	STP_SendSynch(0xBFD8);
	STP_SendSynch(0x7F00);

	STP_SendSynch(0xFE80);
	STP_SendSynch(0xFDE0);
	STP_SendSynch(0xFB00);
	STP_SendSynch(0xF7FC);
	STP_SendSynch(0xEF24);
	STP_SendSynch(0xDFD8);
	STP_SendSynch(0xBF00);
	STP_SendSynch(0x7FF0);

	STP_SendSynch(0xFEE0);
	STP_SendSynch(0xFD00);
	STP_SendSynch(0xFBFC);
	STP_SendSynch(0xF724);
	STP_SendSynch(0xEFD8);
	STP_SendSynch(0xDF00);
	STP_SendSynch(0xBFF0);
	STP_SendSynch(0x7F28);

	STP_SendSynch(0xFE00);
	STP_SendSynch(0xFDFC);
	STP_SendSynch(0xFB24);
	STP_SendSynch(0xF7D8);
	STP_SendSynch(0xEF00);
	STP_SendSynch(0xDFF0);
	STP_SendSynch(0xBF28);
	STP_SendSynch(0x7F28);

	TIM2_voidSetBusyWait(300);
}

void NUM_One(void)
{
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFD00);
	//
	STP_SendSynch(0xFB46);
	//
	STP_SendSynch(0xF743);
	//
	STP_SendSynch(0xEF7F);
	//
	STP_SendSynch(0xDF40);
	//
	STP_SendSynch(0xBF40);
	//
	STP_SendSynch(0xBF00);
	//
	TIM2_voidSetBusyWait(300);
}
void NUM_TWO(void)
{
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFD79);
	//
	STP_SendSynch(0xFB49);
	//
	STP_SendSynch(0xF749);
	//
	STP_SendSynch(0xEF49);
	//
	STP_SendSynch(0xDF4F);
	//
	STP_SendSynch(0xBF00);
	//
	STP_SendSynch(0xBF00);
	//
	TIM2_voidSetBusyWait(300);

}

void NUM_Three(void)
{
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFD49);
	//
	STP_SendSynch(0xFB49);
	//
	STP_SendSynch(0xF749);
	//
	STP_SendSynch(0xEF49);
	//
	STP_SendSynch(0xDF7F);
	//
	STP_SendSynch(0xBF00);
	//
	STP_SendSynch(0xBF00);
	//
	TIM2_voidSetBusyWait(300);

}





void NUM_Four(void)
{
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFD00);
	//
	STP_SendSynch(0xFB1E);
	//
	STP_SendSynch(0xF710);
	//
	STP_SendSynch(0xEF10);
	//
	STP_SendSynch(0xDFFE);
	//
	STP_SendSynch(0xBF00);
	//
	STP_SendSynch(0xBF00);
	//
	TIM2_voidSetBusyWait(300);
}

void NUM_Five(void)
{
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFD3C);
	//
	STP_SendSynch(0xFB04);
	//
	STP_SendSynch(0xF704);
	//
	STP_SendSynch(0xEF3C);
	//
	STP_SendSynch(0xDF20);
	//
	STP_SendSynch(0xBF20);
	//
	STP_SendSynch(0xBF3C);
	//
	TIM2_voidSetBusyWait(300);
}


void NUM_Six(void)
{
	STP_SendSynch(0xFE00);
	//
	STP_SendSynch(0xFD3C);
	//
	STP_SendSynch(0xFB04);
	//
	STP_SendSynch(0xF73C);
	//
	STP_SendSynch(0xEF24);
	//
	STP_SendSynch(0xDF24);
	//
	STP_SendSynch(0xBF3C);
	//
	STP_SendSynch(0xBF00);
	//
	TIM2_voidSetBusyWait(300);
}


